import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillLinkedin,
  AiFillFacebook,
  AiFillTwitterSquare,
} from "react-icons/ai";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import image from "../public/image.png";
import { useState } from "react";
import Card from "../components/Card";
import Skills from "../components/Skills";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>React Tailwind Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 dark:bg-gray-900">
        <section className=" min-h-screen">
          <nav className=" py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-white md:px-10 lg:px-20">
              Developedbyjosh
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="dark:text-white cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  href="#"
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 px-4 py-2 rounded-md ml-8 text-white"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl text-teal-500 font-medium md:text-6xl">
              Joshua Arnaez
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              Fullstack Developer
            </h3>
            <p className="text-md leading-7 py-5 text-gray-600 dark:text-gray-300 md:text-xl max-w-2xl mx-auto">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime
              mollitia, molestiae quas vel sint commodi repudiandae consequuntur
              voluptatum laborum numquam blanditiis harum quisquam eius sed odit
              fugiat iusto fuga praesentium optio, eaque rerum! Provident
              similique accusantium nemo autem
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-10 text-gray-600 dark:text-gray-300">
            <AiFillLinkedin />
            <AiFillFacebook />
            <AiFillTwitterSquare />
          </div>
          <div className="relative mx-auto first-letter:mx-auto bg-gradient-to-b from-teal-500 rounded-full w-64 h-64 overflow-hidden mb-20 md:h-96 md:w-96">
            <Image src={image} alt="image" fill object-fit="cover" />
          </div>
        </section>
        <section>
          <div className="max-w-5xl mx-auto">
            <h3 className="text-3xl py-1 dark:text-white">Services I Offer</h3>
            <p className="text-md leading-7 text-gray-600 dark:text-gray-300 py-3 md:text-xl">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime
              mollitia, molestiae quas vel sint commodi repudiandae consequuntur
              voluptatum laborum <span className="text-teal-500">numquam</span>{" "}
              blanditiis harum quisquam eius sed odit fugiat iusto fuga
              praesentium optio, eaque rerum!
              <span className="text-teal-500">Provident</span>
              similique accusantium nemo autem
            </p>
          </div>
          <div className="my-20  md:flex flex-wrap lg:flex justify-center gap-10">
            <Skills
              image={code}
              header="Website"
              subheader="Language that i use"
            >
              <p className="skillTag">React/Nextjs</p>
              <p className="skillTag">Tailwindcss</p>
              <p className="skillTag">Prisma</p>
              <p className="skillTag">Nodejs</p>
            </Skills>
            <Skills
              image={code}
              header="Website"
              subheader="Language that i use"
            >
              <p className="skillTag">Tailwindcss</p>
              <p className="skillTag">Prisma</p>
              <p className="skillTag">Nodejs</p>
            </Skills>
            <Skills
              image={code}
              header="Website"
              subheader="Language that i use"
            >
              <p className="skillTag">Tailwindcss</p>
              <p className="skillTag">Prisma</p>
              <p className="skillTag">Nodejs</p>
            </Skills>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Portfolio</h3>
            <p className="text-md leading-7 text-gray-600 py-3 md:text-xl dark:text-gray-300">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime
              mollitia, molestiae quas vel sint commodi repudiandae consequuntur
              voluptatum laborum <span className="text-teal-500">numquam</span>{" "}
              blanditiis harum quisquam eius sed odit fugiat iusto fuga
              praesentium optio, eaque rerum!
              <span className="text-teal-500 md:text-xl dark:text-gray-300">
                Provident
              </span>
              similique accusantium nemo autem
            </p>
            <p className="text-md leading-7 text-gray-600 py-3 md:text-xl dark:text-gray-300">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime
              mollitia, molestiae quas vel sint commodi repudiandae consequuntur
              voluptatum laborum
            </p>
          </div>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:grid-cols-3">
            <Card image={web1} />
            <Card image={web2} />
            <Card image={web3} />
            <Card image={web4} />
            <Card image={web5} />
            <Card image={web6} />
          </div>
        </section>
      </main>
      <footer></footer>
    </div>
  );
}
